name = "TruthTables"
uuid = "9ec6d097-1036-44b0-a6be-6d8b59e15e3f"
authors = ["Elias Carvalho <eliascarvdev@gmail.com>"]
version = "0.5.2"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
PrettyTables = "1.3, 2"
Tables = "1.7"
julia = "1.6"
